### ISSUE TITLE
Weird styles behavior on indented blocks

### ISSUE THREAD

**Issue by scriptin** [couzteau/SpellCheck#13]
Hello! I have an issue here: scriptin/brackets-indent-softwraps/issues/4 which explains the problem.

After investigating, I found a quick fix, but not sure if it's correct. In your CSS you have a declaration [`display: inline-block;`](/couzteau/SpellCheck/blob/master/styles.css#L3). If I change this to `inline` (which is default), it gets fixed. I'm not sure if `inline-block` is really required by your plugin to work properly, but it seems to work fine w/o it.

You can see that for some reason when it is `inline-block`, it sets width and height to fixed values. If I set display to `inline`, both width and height have value `auto`.

Can you change it or am I missing something on my side?

![screenshot from 2015-02-10 00 57 39](https://cloud.githubusercontent.com/assets/665888/6116738/1ba5a812-b0c0-11e4-861e-eea5f3d172bd.png)

**Comment by couzteau** [comment]
pushed update. Thanks for finding the issue and providing the fix @scriptin
