### ISSUE TITLE
Update 0.5.8 not compatible for brackets 1.2

### ISSUE THREAD

**Issue by Jackbennett** [couzteau/SpellCheck#15]
I've notice I think for at least Brackets 1.1 and now 1.2 that this Spell-check plugin is listed with an update to 0.5.8 but is greyed out as "The update isn't compatible with this version of brackets."

I'm on Windows 8.1x64 if that matters. Is this right?

**Comment by couzteau** [comment]
I cannot repro the issue you describe. But I don't have you version of Windows to validate. But it shouldn't matter.

**Comment by Jackbennett** [comment]
I still had it stuck like this with brackets 1.3. I just removed and re-added the plugin and it's on 0.5.8.

That was odd.

**Comment by couzteau** [comment]
Thanks for checking and closing. I agree, it's an odd issue. Most likely an issue of  the Brackets Extensions Manager.
